### PR TITLE
fix(test-lint): Add lint fixes and test cases to vue app

### LINKED ISSUE #19: Add lint fixes and test cases to vue app
### Why is this issue created?
- There are a lot of lint errors that need to be fixed which are show by vue-cli lint service
- Test cases are required for the application

### PR DESCRIPTION
**Pull request by hybridx**
Added helloWorld test case and basic lint fix
Added default jest config

Fixes #19 

## Proposed Changes

- Added test for signinPage

### CODE REVIEW

**Comment by aprajshekhar** [comment]
@hybridx , is this still a WIP?

**Comment by hybridx** [comment]
> @hybridx , is this still a WIP?

Apologies for the delay, I see that this is now becoming a blocker as the build is failing because the lint and tests are failing. Will complete this ASAP, as for now it is still WIP

**Comment by hybridx** [comment]
hey @aprajshekhar @Korra15 This is ready for review. We can add more test cases in future additions as well

**Review by aprajshekhar — APPROVED** [review]
Great job. Approved and merging.

**Pull request merged**
