### PR TITLE
ci(fix/#17): Github action to build and test vue-app before each PR 

### LINKED ISSUE #17: Github action to build and test vue-app before each PR
### Need of this issue?
- This would automatically run github action before PR are merged which would help identify any breaking changes in a PR and also dependabot PRs

### PR DESCRIPTION
**Pull request by hybridx**
### What is this fix?
- Resolves #17 
- Added a CI yml to test on each push and pull request, this would be run by github actions

### Extra information?
Added an extra feature of using GabrielBB for a future usescase where we can also run browser tests which needs xvfb

### Breaking changes?
None

### CODE REVIEW

**Review by aprajshekhar — APPROVED** [review]
Thanks for this PR. LGTM.

**Comment by aprajshekhar** [comment]
@hybridx please go ahead and merge.

**Comment by hybridx** [comment]
> @hybridx please go ahead and merge.

@aprajshekhar This seems like an protected branch, I don't have access to it. Is there a develop branch that I missed?
Screenshot 2021-09-26 at 10 15 14 PM

**Comment by aprajshekhar** [comment]
@hybridx sorry for that. I have merged the PR. Again thanks for the contribution.

**Pull request merged**
